// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Notification
{
    public int Id { get; set; }

    public string Message { get; set; }

    public string Channel { get; set; }

    public string Recipient { get; set; }

    public string Timezone { get; set; }

    public DateTime? Scheduled { get; set; }

    public bool? Sent { get; set; }
}